/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generic.Maximum;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class MaximumJUnitTest {
    @Test
    public void testMaximum1() {
    	MaximumTest intMaxTest = new MaximumTest();
    	boolean found = false;
    	if(intMaxTest.maximum("Peach","Banana","Apple") == "Peach") {
    		found = true;
    	}
    	Assert.assertTrue(found);
    }
    @Test
    public void testMaximum2() {
    	MaximumTest intMaxTest = new MaximumTest();
    	boolean found = false;
    	if(intMaxTest.maximum("Banana","Peach","Apple") == "Peach") {
    		found = true;
    	}
    	Assert.assertTrue(found);
    }
    @Test
    public void testMaximum3() {
    	MaximumTest intMaxTest = new MaximumTest();
    	boolean found = false;
    	if(intMaxTest.maximum("Apple","Banana","Peach") == "Peach") {
    		found = true;
    	}
    	Assert.assertTrue(found);
    }
}
