/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generic.Maximum;

import java.util.ArrayList;
import java.util.Collections;

public class MaximumTest <E extends Comparable<E>> {
	E a, b, c, d, e;
	ArrayList<E> arr = new ArrayList<E>();
	
	public MaximumTest(E a, E b, E c, E d, E e) {
		this.a = a;
		this.b = b;
		this.c = c;
		this.d = d;
		this.e = e;
	}
	
	public ArrayList<E> addValues(){
		arr.add(a);
		arr.add(b);
		arr.add(c);
		arr.add(d);
		arr.add(e);
		
		return arr;
	}
	
    public static <E extends Comparable<E>> E maximum(ArrayList<E> arr) {
    	Collections.sort(arr);
    	printMax(arr);
    	return arr.get(arr.size()-1);
    }
    
    public static <E> void printMax(ArrayList<E> arr) {
    	System.out.println(arr.get(arr.size()-1));
    }
}
