/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generic.Maximum;

public class MaximumTest <E extends Comparable<E>> {
	E a, b, c;
	
	public MaximumTest(E a, E b, E c) {
		this.a = a;
		this.b = b;
		this.c = c;
	}
	
	public static <E extends Comparable<E>> E maximum(E a, E b, E c){
		E max = a;
		if(b.compareTo(max) > 0) {
			max = b;
		}
		if(c.compareTo(max) > 0) {
			max = c;
		}
		return max;
	}
    
}
