/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generic.Maximum;

public class MaximumTest {
    public static Integer maximum(Integer a, Integer b, Integer c) {
    	Integer max = a;
    	if(b.compareTo(max) > 0) {
    		max = b;
    	}
    	if(c.compareTo(max) > 0) {
    		max = c;
    	}
    	return max;
    }
    
    public static Double maximum(Double a, Double b, Double c) {
    	Double max = a;
    	if(b.compareTo(max) > 0) {
    		max = b;
    	}
    	if(c.compareTo(max) > 0) {
    		max = c;
    	}
    	return max;
    }
}
